name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install libssl-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Upload build result
      uses: actions/upload-artifact@v2.3.1
      with:
        path: "target/release/hellojudge3-judger"
