name: Build binary

on:
  push:
    tags:
      - v**
  pull_request:


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt install libssl-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Rename binary
      id: rename
      shell: bash
      run: |
        BIN="hellojudge3-judger_linux_amd64"
        mv target/release/hellojudge3-judger target/release/$BIN
        echo "::set-output name=bin::target/release/$BIN"
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: |
          target/release/hellojudge3-judger*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ steps.rename.outputs.bin }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
